language: php
php:
    - 5.3.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm


matrix:
    allow_failures:
        - php: hhvm
        - php: 5.3.3


before_script:
    # Install Code Checker
    - travis_retry composer install --no-interaction --prefer-dist
    - travis_retry composer create-project nette/code-checker code-checker ~2.2 --no-interaction --prefer-source


script:
    - php code-checker/src/code-checker.php -d libs
    - vendor/bin/phpunit


cache:
    directories:
        - $HOME/.composer/cache
